# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geometric Computing for Virtual Environments [MAT 200C]
email: wolftype -> gmail
description: > # 
  A course exploring computational geometry using linear and 
  geometric algebras as core synthesis tools to create virtual environments. 
baseurl: "/200c" # the subpath of your site, e.g. /blog
url: "http://wolftype.github.io/200c" # the base hostname & protocol for your site
github_username:  wolftype

# Build settings
markdown: kramdown
